---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# metamed

<!-- badges: start -->
<!-- badges: end -->

The goal of metamed is to ...

## Installation

You can install the development version of metamed like so:

``` r
install.packages("remotes")
remotes::install_github("umarhussain-git/metamed")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(metamed)
library(metamed)

dat <- data.frame(
Study = c("Shell 2021","Khalid 2020","Daniel 2009","Albert 2018","Khan 2011"),
events_t = c(10,25,5,30,18),
n_t = c(100,120,90,140,110),
events_c = c(15,20,22,28,25),
n_c = c(100,115,95,130,120)
)

forest.binary(
dat,
measure = "OR"
)

# Example for continuous outcome

dat_cont <- data.frame(

Study = c("Study A","Study B","Study C"),

mean_t = c(5.2,6.1,4.8),

sd_t = c(1.2,1.5,1.1),

 n_t = c(30,25,28),

 mean_c = c(4.8,5.5,4.5),

 sd_c = c(1.0,1.3,1.2),

 n_c = c(28,27,30)

 )

 forest.continuous(dat_cont)

```



You'll still need to render `README.Rmd` regularly, to keep `README.md` up-to-date. `devtools::build_readme()` is handy for this.


